plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
